import { existsSync } from "fs";
import { join, relative } from "path";
import { fileURLToPath } from "url";

import type { AstroConfig, AstroIntegration, AstroIntegrationLogger, InjectedRoute } from "astro";
import { addVirtualImports } from "astro-integration-kit";
import { writeFile, mkdir } from "fs/promises";
import { glob } from "tinyglobby";

import { generateSchemaEndpoint, schemaFileName, type SchemaGeneratorOptions } from "./generate/schema";
import { getClientRouteMap, getServerRouteMap, getRouteTypes, referenceTypes, virtual } from "./generate/types";
import type { SelfResolvedEndpoints } from "./generate/types";

export type Options = {
	/**
	 * Generate an OpenAPI schema for the endpoints
	 *
	 * Pass an object to customize options
	 */
	generateSchema?: boolean | Partial<SchemaGeneratorOptions>;

	/**
	 * Options for generating virtual modules as real `.ts` files instead
	 *
	 * Remove the option if generating `.ts` files is not desired
	 */
	generateRealVirtualModules?: boolean | {
		/**
		 * Path for generating .ts from virtual modules,
	 	 * relative to `src`
		 */
		path?: string;

		/**
		 * Path for generating the openapi.json.ts endpoint,
	 	 * relative to `src`.
		 *
		 * Only works if `options.generateSchema.virtual` is `false`.
		 *
		 * Overwrites `options.generateSchema.url`.
		 *
		 * @default `pages/openapi.json.ts`
		 */
		schemaPath?: string;

		/**
		 * Prepend a string at the start of a file
		 *
		 * @example can be used to prepend a linter directive
		 * to make the linter skip analyzing these files,
		 * in case they violate the project's lint rules:
		 * ```
		 * head: `// eslint-disable`
		 * ```
		 */
		head?: string;
	};

	/**
	 * Select which endpoints to process via a glob pattern
	 *
	 * Default preset is aligned with Astro: skip `.ts` files that start with `_`
	 * @default "**\/[!{_}]*.{ts,mts}"
	 */
	endpointsGlob?: string;

	/**
	 * Where to look for the endpoints in the `src` folder
	 *
	 * @default `pages`
	 */
	endpointsRoot?: string;
};

const declarationFile = "api.d.ts";

export default function (options?: Options): AstroIntegration {
	let params: Parameters<Exclude<AstroIntegration["hooks"]["astro:config:setup"], undefined>>[0];
	let endpoints: SelfResolvedEndpoints[] = [];
	let roots: string[] = [];
	let schemaFile: URL;
	let cwd: URL;

	const resolvedGenerateSchemaOptions = {
		title: "OpenAPI Schema",
		version: "1.0.0",
		servers: [{ url: "/" }],
		url: "/openapi.json",
		...(
			typeof options?.generateSchema === "boolean"
				? {}
				: options?.generateSchema
		)
	};

	const resolvedGenerateVirtualModulesOptions = {
		head: `/* Generated by astro-typesafe-api, do not edit */`,
		schemaPath: `${options?.endpointsRoot ?? "pages"}/${schemaFileName}`,
		...typeof options?.generateRealVirtualModules === "object"
			? options.generateRealVirtualModules
			: {}
	};

	return {
		name: "astro-typesafe-api",
		hooks: {
			async "astro:config:setup"(_params) {
				const { updateConfig, config, createCodegenDir, logger, injectRoute } = params = _params;
				const codegenDir = createCodegenDir();
				schemaFile = new URL(schemaFileName, codegenDir);

				updateConfig({
					vite: {
						optimizeDeps: {
							exclude: ["astro-typesafe-api"],
						},
						define: {
							"import.meta.env._TRAILING_SLASH": JSON.stringify(
								config.trailingSlash
							),
						},
						ssr: {
							// this package is published as uncompiled typescript, which we need vite to process
							noExternal: ["astro-typesafe-api"],
						},
					},
				});

				cwd = new URL(options?.endpointsRoot || "pages", params.config.srcDir);

				// Get all non-ignored endpoints from the pages dir
				const endpointFiles = (await glob(
					options?.endpointsGlob ?? "**/[!{_}]*.{ts,mts}",
					{ cwd }
				)).filter(f => !f.endsWith(schemaFileName));

				endpoints = endpointFiles.map(e => ({
					entrypoint: join(relative(config.srcDir.pathname, cwd.pathname), e).replaceAll("\\", "/"),
					pattern: e.replace(/(?:index)?\.m?ts$/, "")
				}));

				roots = endpoints
					.map(r => r.pattern.split("/")[0])
					.filter((v, i, a) => a.indexOf(v) === i);

				logger.info(`Found ${roots.length} endpoint root(s)`);

				if (!options?.generateRealVirtualModules) {
					addVirtualImports(params, {
						name: "astro-typesafe-api",
						imports: [{
							id: virtual.api,
							content: `export * from "astro-typesafe-api/server";`,
							context: "server"
						}, {
							id: virtual.client,
							content: getClientRouteMap(roots),
							context: "client",
						}, {
							id: virtual.server,
							content: getServerRouteMap(roots, endpoints),
							context: "server"
						}]
					});

					logger.info(`Generated virtual modules`);
				}

				await maybeGenerateRealModules(config, codegenDir, logger);

				await maybeGenerateSchema(config.root, injectRoute, logger);
			},

			"astro:config:done"({ injectTypes, logger }) {
				injectTypes({
					filename: declarationFile,
					content: getRouteTypes(roots, endpoints, !options?.generateRealVirtualModules)
				});

				logger.info("Updated astro types");
			},
		},
	};

	async function maybeGenerateSchema(
		root: URL,
		injectRoute: (injectRoute: InjectedRoute) => void,
		logger: AstroIntegrationLogger
	) {
		if (!options?.generateSchema) {
			return;
		}

		const schema = generateSchemaEndpoint(endpoints, resolvedGenerateSchemaOptions);

		await writeFile(schemaFile, schema);

		if (
			!resolvedGenerateVirtualModulesOptions.schemaPath
			|| resolvedGenerateSchemaOptions.virtual !== false
		) {
			injectRoute({
				entrypoint: schemaFile,
				pattern: resolvedGenerateSchemaOptions.url,
				prerender: resolvedGenerateSchemaOptions.prerender ?? true,
			});

			logger.info(`Injected an OpenAPI document virtual route at ${resolvedGenerateSchemaOptions.url}`);
		} else {
			// Generate real module 👇
			const {
				head,
				schemaPath
			} = resolvedGenerateVirtualModulesOptions;

			const finalSchemaPath = new URL(schemaPath, cwd);

			await writeFile(
				finalSchemaPath,
				`${head}\n${schema}`
			);

			logger.info(`Generated an OpenAPI document route at ${
				relative(fileURLToPath(root), fileURLToPath(finalSchemaPath)).replace(/\\/g, "/")
			}`);
		}
	}

	async function maybeGenerateRealModules(
		config: AstroConfig,
		codegenDir: URL,
		logger: AstroIntegrationLogger
	) {
		if (options?.generateRealVirtualModules) {
			const {
				head,
				path,
			} = resolvedGenerateVirtualModulesOptions;

			const modulesDir = path
				? join(fileURLToPath(config.srcDir), path)
				: fileURLToPath(codegenDir);

			const referencePath = referenceTypes(
				modulesDir,
				".astro/types.d.ts",
				fileURLToPath(config.root)
			);

			if (!existsSync(modulesDir)) await mkdir(modulesDir);

			const imports = [{
				id: virtual.api,
				content: `export * from "astro-typesafe-api/server";`,
				context: "server"
			}, {
				id: virtual.client,
				content: getClientRouteMap(roots, true),
				context: "client",
			}, {
				id: virtual.server,
				content: getServerRouteMap(roots, endpoints, true),
				context: "server"
			}];

			for (const module of imports) {
				await writeFile(
					join(modulesDir, `${module.id.replace(/.*?:/, "")}.ts`),
					`${head}\n${referencePath}\n${module.content}`,
					{ encoding: "utf8" }
				);
			}

			logger.info(`Generated .ts files from virtual modules at ${
				relative(fileURLToPath(config.root), modulesDir).replace(/\\/g, "/")
			}`);
		}
	}
}
